name: "semver"
version: "0.2.0"
usage: "helm semver show  -c <chart-path> or helm semver update [major|minor|patch|premajor|preminor|prepatch|prerelease] --preid [alpha|rc] -c <chart-path>"
description: "A Helm plugin to update Chart.yaml version."
command: "node $HELM_PLUGIN_DIR/build/index.js"